name: "Hello to You Docker"
description: "Prints a greeting message in a Docker container"
inputs:
  name:
    required: true
    description: "Your name"
    default: "World"
runs:
  using: docker
  image: dockerfile