name: 03 - runners de workflow
on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: "Mostrar SO"
              run: | 
                    echo "Este trabajo se ejecuta en runner de ubuntu" 
                    echo $RUNNER_OS
              