name: 04 -  Uso de Actions
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "checkout code"
              uses: Actions/checkout@v6
            - name: "node setup"
              run: Actions/setup-node@v4
            - name: "install dependencies"
              working-directory: ./my-app
              run: npm ci
            

