name: 07 - Contexts
run-name: ${{ inputs.debug && 'DEBUG MODE' || 'Normal Run' }}
on: 
    #push:
    workflow_dispatch:
    #    inputs:
    #        debug:
    #            description: "debug mode"
    #            type: boolean
    #            default: false
jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: "show Github Context"
              run: |
                    echo "Event: ${{github.event_name}}"
                    echo "Ref: ${{github.ref}}"
                    echo "SHA: ${{github.workflow_sha}}"
                    echo "Actor: ${{github.actor}}"
                    echo "Workflow: ${{github.workflow}}"
            - name: "Retrieve Variable"
              run: 'echo "Imprimos el valor de la variable añadida al repositorio llamada MY_VAR: ${{vars.MY_VAR}}"'